### PR TITLE
Update travis config, node 10 & dependencies

### PR DESCRIPTION
**Pull request by Nargonath**
I wasn't sure you'd want to remove the node 8 & 10 versions so I left them here. I believe you'll want to make a breaking change to change that.

### CODE REVIEW

**Comment by devinivy** [comment]
Thanks!  This work will be done as a part of https://github.com/hapipal/hpal/issues/51, so it's fine to make that breaking change here.

**Comment by Nargonath** [comment]
Alright I'll change that then. I just updated the file since I made a mistake. It seems you can have only one `import` key in your config file so I updated it to use the array version.

**Comment by Nargonath** [comment]
There seem to be a timeout on the test for `hpal new` on Windows with node@14.

**Comment by Nargonath** [comment]
I dug more into updating `marked` and `marked-terminal`. `marked@1.0.0` introduced breaking changes in the way tokens are structured for composite markdown elements i.e lists, blocks. Previously tokens were a flat array list even for composite elements i.e for a heading with a list and one item you had:

```
{
  { type: 'heading' },
  { type: 'list_start' },
  { type: 'list_item_start' },
  { type: 'paragraph' },
  { type: 'list_item_end' },
  { type: 'list_end' }
]
```

However they changed that structure and now composite elements have nested children. Here is how it looks like now for the same structure mentioned above:

```
{
  { type: 'heading' },
  { type: 'list', tokens: [
    { type: 'list_item', tokens: [
      { type: 'paragraph' } 
    ] } 
  ] }
]
```

This has impact on the way hpal parses the markdown content hence multiple tests are now failing (~7 tests). I started working on updating the code base to handle the new token format. I started on this function: https://github.com/hapipal/hpal/blob/dae9481c7adc13cc6ce90c7241e82efea41cb497/lib/print.js#L221. Just to make sure I understand it correctly, @devinivy can you confirm: we keep the whole content of the first list we encounter which has its first child whose content matches the list item matcher?

For more information, see:
- https://github.com/markedjs/marked/pull/1627#issuecomment-606753680
- https://github.com/markedjs/marked/pull/1627#issuecomment-607843930

**Comment by devinivy** [comment]
@Nargonath Oh my!  Haha, I did not anticipate running into changes to marked's lexer, but I suppose one ought to expect the unexpected these days.

> Just to make sure I understand it correctly, @devinivy can you confirm: we keep the whole content of the first list we encounter which has its first child whose content matches the list item matcher?

Actually I think the intent is to just pick out the list item and any of its sub-items if it has a deeper list beneath it.  Here's an example of what you see from the user's perspective.

**Finding a markdown section**
```
❯ npx hpal docs expose         

Searching docs from hapijs/hapi @ master...

### server.expose(key, value, [options])

Used within a plugin to expose a property via server.plugins[name] (#server.plugins) where:

    * key - the key assigned (server.plugins[name][key] (#server.plugins)).
    * value - the value assigned.
    * options - optional settings:
        * scope - controls how to handle the presence of a plugin scope in the name (e.g. @hapi/test):
        ...
```

**Finding a markdown list item**
(I believe this is the case you're talking about: you can see it's just the one list item and its sub-items.)
```
❯ npx hpal docs expose options

Searching docs from hapijs/hapi @ master...

### server.expose(key, value, [options])

    * options - optional settings:
        * scope - controls how to handle the presence of a plugin scope in the name (e.g. @hapi/test):
        ...
```

**Comment by Nargonath** [comment]
Alright thanks for the explanation. I should have enough information to proceed with the changes otherwise I'll come back with some more questions. 😄

**Comment by devinivy** [comment]
Hey @Nargonath I ended-up making some headway on the marked updates: https://github.com/hapipal/hpal/commit/14e51fca187fd2057ea8e60ad375d65f821dd975

This should be ready for merge soon 👍

**Comment by Nargonath** [comment]
@devinivy Cool! Sorry I didn't get time to go back on it with the GH Actions migration on hapi side. Do you want me to rebase the PR to the v3 branch?

**Comment by devinivy** [comment]
@Nargonath actually this is already in the v3 branch!  Unfortunately I can't change the base branch of this PR to v3, so let's just let it hang around and close itself when the v3 branch is merged to master.  You work here is done, thank you! 💯

**Comment by Nargonath** [comment]
Oh ok cool. 👍

**Pull request merged**
